service: product-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: "3"

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: true

provider:
  name: aws
  runtime: nodejs20.x
  region: "us-west-1"

functions:
  getProductById:
    handler: handler.getProductById
    events:
      - httpApi:
          method: get
          path: /products/{productId}
          cors: true
          request:
            parameters:
              paths:
                productId: true

  getAllProducts:
    handler: handler.getAllProducts
    events:
      - httpApi:
          method: get
          path: /products
          cors: true
