service: product-service
frameworkVersion: "3"

plugins:
  - serverless-auto-swagger
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: "eu-west-1"
  stage: ${opt:stage, 'dev'}
  apiGateway:
    apiKeySourceType: HEADER
    minimumCompressionSize: 1024

  httpApi:
    cors: true

  iam:
    role:
      name: "DynamoDB"
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "arn:aws:dynamodb:eu-west-1:381492192203:table/products"
            - "arn:aws:dynamodb:eu-west-1:381492192203:table/stocks"

custom:
  stage: ${opt:stage, self:provider.stage}
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: true

functions:
  getProductById:
    handler: handler.getProductById
    events:
      - httpApi:
          method: GET
          path: /${self:custom.stage}/products/{productId}

  getAllProducts:
    handler: handler.getAllProducts
    events:
      - httpApi:
          method: GET
          path: /${self:custom.stage}/products
