service: product-service
frameworkVersion: "3"

plugins:
  - serverless-auto-swagger
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: true

provider:
  name: aws
  runtime: nodejs20.x
  region: "eu-west-1"
  stage: ${opt:stage, 'dev'}
  httpApi:
    cors: true

functions:
  getProductById:
    handler: handler.getProductById
    events:
      - httpApi:
          method: GET
          path: /products/{productId}

  getAllProducts:
    handler: handler.getAllProducts
    events:
      - httpApi:
          method: GET
          path: /products
