service: game-store-cart-api

plugins:
  - serverless-offline

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: 'eu-west-1'
  stage: ${opt:stage, 'dev'}
  environment:
    DB_USER: ${env:DB_USER}
    DB_SERVER: ${env:DB_SERVER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_PORT: ${env:DB_PORT}
    DB_DATABASE: ${env:DB_DATABASE}

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
