service: import-service
frameworkVersion: "3"

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: "eu-west-1"
  stage: ${opt:stage, 'dev'}
  environment:
    BUCKET_NAME: game-store-nodejs-aws-assets
    ASSET_FOLDER_NAME: uploaded
  httpApi:
    cors: true
  iam:
    role:
      name: "S3-assets-uploader"
      statements:
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource:
            - "arn:aws:s3:::${self.provider.environment.bucketName}"

custom:
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: true

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - httpApi:
          method: get
          path: /${self:provider.stage}/import
